@startuml
title Информационная система жилищного агентства: диаграмма последовательности
skinparam backgroundcolor AntiqueWhite/Green
participant Квартиросъемщик
participant Заявка
participant Система
participant Владелец_жилья
activate Квартиросъемщик
Квартиросъемщик -> Заявка: подает заявку
activate Заявка
Заявка -> Система: Подача заявки
deactivate Квартиросъемщик
activate Система
Система -> Заявка: Оценивает заявку
Заявка-> Владелец_жилья: Заявка одобрена
deactivate Заявка
activate Владелец_жилья
Владелец_жилья -> Заявка: Принимает заявку
deactivate Владелец_жилья
activate Заявка
Владелец_жилья -> Квартиросъемщик: Выдает жилье
deactivate Владелец_жилья
activate Квартиросъемщик
@enduml 
Диаграмма развертывания
@startuml
left to right direction
title Информационная система жилищного агентства: диаграмма развертывания
skinparam backgroundcolor AntiqueWhite/Green
database Система
node Заявка
node ПК_Квартиросъемщик
node ПК_Владелец_жилья
ПК_Квартиросъемщик - Заявка: Подает
Заявка - Система: Поступает
ПК_Владелец_жилья -- Заявка: Приходит
ПК_Владелец_жилья ..> ПК_Квартиросъемщик: Высылает договор о съеме жилья
@enduml
