@startuml
left to right direction
actor владелец_жилья
actor квартиросъемщик
rectangle информационная_система {
  квартиросъемщик--(подача заявки)
  (подача заявки) ..>(система)
  (система) ..> (предложение_о_жилье)
  (предложение_о_жилье) ..> (квартиросъемщик)
  (квартиросъемщик) -- (сделка)
  (сделка) ..> (владелец_жилья)
}
@enduml 

class владелец_жилья {
+фио
+пол
+номер телефона
}


class квартиросъемщик {
+фио
+пол
+номер телефона
+паспортные данные

}


class заявка {
+количество комнат
+метро
+адрес
+цена
+жилплощадь
+общая площадь
+этаж
+расположение метро
+цена
+наличе мебели
} 
class сделка {
+фио_владелеца_жилья
+пол_владелеца_жилья
+номер телефона_владелеца_жилья
+паспортные данные_владелеца_жилья
+фио_квартиросъемщика
+пол_квартиросъемщика
+номер телефона_квартиросъемщика
+паспортные данные_квартиросъемщика

}
квартиросъемщик ..>заявка
заявка ..> владелец_жилья
квартиросъемщик -- сделка
сделка -- владелец_жилья
