@startuml
left to right direction
skinparam packageStyle rect

actor владелец_жилья
actor квартиросъемщик

rectangle информационная_система {
  
  квартиросъемщик--(характеристика квартиры)
  квартиросъемщик--(выгодная сделка)
  квартиросъемщик--(описание квартиры)
  

  (выгодная сделка) .> (сдача квартиры)

  владелец_жилья--(предложение по сдаче квартиры)
  владелец_жилья--(сдача квартиры)
  
}
@enduml
